name: Add Label to Issues

on:
  issues:
    types: [opened, edited]
    
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: christianvuerings/add-labels@v1
        if: ${{ github.event.issue.state == 'open' && (contains(github.event.issue.body, 'The bug prevents users from completing critical tasks (e.g., saving data)') || contains(github.event.issue.body, 'The bug prevents users from completing some tasks')) }}
        with:
          labels: |
            High Priority
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      - uses: christianvuerings/add-labels@v1
        if: ${{ github.event.issue.state == 'open' && contains(github.event.issue.body, 'The bug prevents users from completing some tasks') }}
        with:
          labels: |
            Medium Priority
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
