name: Add Label to Issues

on:
  issues:
    types: [opened, edited]
    
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: achoobert/action-add-labels@main
        if: ${{ github.event.issue.state == 'open' && (contains(github.event.issue.body, 'The bug prevents users from completing critical tasks (e.g., saving data)') || contains(github.event.issue.body, 'The bug prevents users from completing some tasks')) }}
        with:
          labels: |
            High Priority
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create the Mattermost Message
        run: |
          echo "{\"text\":\"A new HIGH PRIORITY issue - it may be an incident. Link: ${{ github.event.issue.html_url }}\", \"channel\":\"NS Products\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        if: ${{ github.event.issue.state == 'open' && (contains(github.event.issue.body, 'The bug prevents users from completing critical tasks (e.g., saving data)') || contains(github.event.issue.body, 'The bug prevents users from completing some tasks')) }}
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}

      
      - uses: achoobert/action-add-labels@main
        if: ${{ github.event.issue.state == 'open' && contains(github.event.issue.body, 'The bug prevents users from completing some tasks') }}
        with:
          labels: |
            Medium Priority
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create the Mattermost Message
        run: |
          echo "{\"text\":\"An issue that might be an incident. Link: ${{ github.event.issue.html_url }}\", \"channel\":\"cars\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        if: ${{ github.event.issue.state == 'open' && contains(github.event.issue.body, 'The bug prevents users from completing some tasks') }}
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
