name: Add Label to Issues

on:
  issues:
    types: [opened, edited]
    
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add High Priority and Incident labels
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            High Priority, Incident
          when: ${{ github.event.issue.state == 'open' && (contains(github.event.issue.body, 'The bug prevents users from completing critical tasks (e.g., saving data)') || contains(github.event.issue.body, 'The bug prevents users from completing some tasks')) }}
      
      - name: Add Medium Priority and Incident labels
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Medium Priority, Incident
          when: ${{ github.event.issue.state == 'open' && contains(github.event.issue.body, 'The bug prevents users from completing some tasks') }}
