name: Add Label to Issues

on:
  issues:
    types: [opened, edited]
    
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - name: Check if Incident label exists and add it
        uses: achoobert/createLabel@main
        with:
          label_name: 'Incident'
          label_color: '000000'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add High Priority and Incident labels
        if: ${{ steps.incident-label.outputs.label-exists == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            High Priority, Incident
          when: ${{ github.event.issue.state == 'open' && (contains(github.event.issue.body, 'The bug prevents users from completing critical tasks (e.g., saving data)') || contains(github.event.issue.body, 'The bug prevents users from completing some tasks')) }}
      
      - name: Add Medium Priority and Incident labels
        if: ${{ steps.incident-label.outputs.label-exists == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Medium Priority, Incident
          when: ${{ github.event.issue.state == 'open' && contains(github.event.issue.body, 'The bug prevents users from completing some tasks') }}
