name: Add Label to Issues

on:
  issues:
    types: [opened, edited]
    
jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add High Priority and Incident labels
        if: ${{ github.event.issue.state == 'open' && (contains(github.event.issue.body, 'The bug prevents users from completing critical tasks (e.g., saving data)') || contains(github.event.issue.body, 'The bug prevents users from completing some tasks')) }}
        uses: Achoobert/action-add-labels@main
        with:
          labels: |
            High Priority, Incident
      
      - name: Add Medium Priority and Incident labels
        if: ${{ github.event.issue.state == 'open' && contains(github.event.issue.body, 'The bug prevents users from completing some tasks') }}
        uses: Achoobert/action-add-labels@main
        with:
          labels: |
            Medium Priority, Incident
