name: Add Label to Issues

on:
  issues:
    types: [opened, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if labels exist
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/labels/Incident)
          if [ $response == "404" ]; then
            echo "Incident label not found"
            echo "created=false" >> $GITHUB_ENV
            labels=("High Priority,ff0000" "Medium Priority,ff9900" "Incident,000000")
            for label in "${labels[@]}"; do
              name=$(echo "$label" | cut -d',' -f1)
              color=$(echo "$label" | cut -d',' -f2)
              if ! github api -X GET /repos/${GITHUB_REPOSITORY}/labels/$name > /dev/null 2>&1; then
                github api -X POST /repos/${GITHUB_REPOSITORY}/labels -F name="$name" -F color="$color"
                echo "created=true" >> $GITHUB_ENV
              fi
            done
            exit 0
          else
            echo "Incident label found"
            exit 0
          fi
        id: incident-label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add High Priority and Incident labels
        if: ${{ steps.incident-label.outputs.label-exists == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            High Priority, Incident
          when: ${{ github.event.issue.state == 'open' && (contains(github.event.issue.body, 'The bug prevents users from completing critical tasks (e.g., saving data)') || contains(github.event.issue.body, 'The bug prevents users from completing some tasks')) }}
      
      - name: Add Medium Priority and Incident labels
        if: ${{ steps.incident-label.outputs.label-exists == 'true' }}
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Medium Priority, Incident
          when: ${{ github.event.issue.state == 'open' && contains(github.event.issue.body, 'The bug prevents users from completing some tasks') }}
